### ISSUE TITLE
Upload de Imagem

### ISSUE THREAD

**Issue by fuhr-br** [LeoBzs/FrontEndAirBnbClone#15]
- [x] Criar um campo no formulário de adicionar um imóvel para enviar uma imagem ao backend
- [x] Criar um http.POST para inserir a  imagem no back( https://airbnd-clone-back-springboot.herokuapp.com/imagem/upload )
- [x] Resgatar a resposta que virá do servidor e armazenar em uma string
- [x] Usar a string para setar o campo imovel.imagemURL antes de cadastrar o imovel no banco de dados
- [x] Usar a URL da imagem para mostrar uma imagem real do imóvel, trocar as imagens mocadas pela propriedade imovel.imagemURL

**Comment by LeoBzs** [comment]
Resolvido de uma maneira mais simples, dentro do próprio método POST do cadastro, enviando a string pro array do imóvel.
