### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by LeoBzs** [LeoBzs/FrontEndAirBnbClone#16]
- [x] Adicionar no layout de procura de imóveis, uma melhor descrição que a busca é por bairro para orientar o usuário

**Comment by fuhr-br** [comment]
![image](https://user-images.githubusercontent.com/58981492/143320513-80b0f570-fd43-4a5e-9cd9-c8d8b8fbf963.png)
Está tela não fala que é por bairro nem que é somente em "Porto Alegre"
