### ISSUE TITLE
Comunicação com o servidor, upgrade estético

### ISSUE THREAD

**Issue by LeoBzs** [LeoBzs/FrontEndAirBnbClone#4]
- [x] #10
- [x] #11
- [x] fetch de dados do servidor
- [x] conversão de dados para os arrays JSON a se comunicarem com o front-end

**Comment by fuhr-br** [comment]
Implementei algumas melhorias no layout dos formulários e adicionei uma tela de login. 
![image](https://user-images.githubusercontent.com/58981492/142916728-5dfc2c79-d48a-47b5-8f1b-6904004569a8.png)
Irei fazer a validação do login
